version: '3.7'

services:

    fpm:
      build:
        context: .
        dockerfile: ./docker/Php7/DockerFile
      volumes:
        - .:/var/www/html
      ports:
        - "9000:9000"
      links:
        - mysql
    
    nginx:
      build:
        context: .
        dockerfile: ./docker/nginx/DockerFile
      volumes:
        - ./:/var/www/
        - ./run/nginx.conf:/etc/nginx/nginx.conf
        - ./run/app.vhost:/etc/nginx/conf.d/app.vhost
        - ./run:/var/log/nginx
      ports:
        - "80:80"
        - "443:443"
      links:
        - fpm
    

    mysql:
      image: mysql:5.7
      container_name: mysql
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=db
        - MYSQL_USER=dbuser
      ports:
        - 33061:3306
      volumes:
        - ./run/var:/var/lib/mysql
      

networks:
  backend:
    name: backend-network

   