version: '3.8'

services:

    fpm:
      build:
        context: .
        dockerfile: ./docker/Php7/DockerFile
      volumes:
        - .:/var/www/html
      ports:
        - "9000:9000"
      links:
        - mysql
    
  
    
    nginx:
      build:
        context: .
        dockerfile: ./docker/nginx/DockerFile
      volumes:
        - ./:/var/www/html
        - ./run/nginx.conf:/etc/nginx/nginx.conf
        - ./run/app.vhost:/etc/nginx/conf.d/app.vhost
        - ./run:/var/log/nginx
      ports:
        - "80:80"
        - "443:443"
      links:
        - fpm
     
    

    mysql:
      image: mysql:5.6
      container_name: mysql
      command: mysqld --user=root --verbose
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=laravel
        - MYSQL_USER=root
      ports:
        - 33061:3306
      volumes:
        - ./run/var:/var/lib/mysql
      
      
       
networks:
  backend:
    driver: bridge

   